[package]
name = "boid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
micromath = { version = "2.0.0", features = ["vector"] }
uefi = "0.18.0"
uefi-services = "0.15.0"
